config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  devise_for :users

  namespace :admin do
    resources :sessions, path: '/login', only: [:new, :create, :destroy]
    resources :users, only: [:index, :edit, :update]
  end

  resources :procesos

  resources :objetivos

  resources :indicadors do
    resources :loginds 
    resources :comments
  end
  

  resources :variables

  resources :logvars

  resources :loginds

  resources :logpros

  authenticated :user do
    root 'procesos#index', as: "authenticated_root"
  end
  
  

  root 'welcome#index'

    get '/login' => 'devise/sessions#new'

end

app/models/logvar.rb
class Logvar < ActiveRecord::Base
  belongs_to :variable
  validates :valor, presence: true
 
	  def to_i
	    valor
	  end



  def self.sum(variable)
  	variable.to_i + variable.to_i
  end

  def self.subst(variable)
  	variable.to_i - variable.to_i
  end


end

app/controllers/logvars_controller.rb
class LogvarsController < ApplicationController
  before_action :set_logvar, only: [:show, :edit, :update, :destroy]

  # GET /logvars
  # GET /logvars.json
  def index
    @logvars = Logvar.all
  end

  # GET /logvars/1
  # GET /logvars/1.json
  def show
  end

  # GET /logvars/new
  def new
    @logvar = Logvar.new
  end

  # GET /logvars/1/edit
  def edit
  end

  # POST /logvars
  # POST /logvars.json
  def create
    @logvar = Logvar.new(logvar_params)

    respond_to do |format|
      if @logvar.save
        format.html { redirect_to @logvar, notice: 'Logvar was successfully created.' }
        format.json { render :show, status: :created, location: @logvar }
      else
        format.html { render :new }
        format.json { render json: @logvar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logvars/1
  # PATCH/PUT /logvars/1.json
  def update
    respond_to do |format|
      if @logvar.update(logvar_params)
        format.html { redirect_to @logvar, notice: 'Logvar was successfully updated.' }
        format.json { render :show, status: :ok, location: @logvar }
      else
        format.html { render :edit }
        format.json { render json: @logvar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logvars/1
  # DELETE /logvars/1.json
  def destroy
    @logvar.destroy
    respond_to do |format|
      format.html { redirect_to logvars_url, notice: 'Logvar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_logvar
      @logvar = Logvar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def logvar_params
      params.require(:logvar).permit(:valor, :fechaD, :variable_id)
    end
end

app/helpers/logvars_helper.rb
module LogvarsHelper
end

app/views/logvars/_form.html.erb
<%= form_for(@logvar) do |f| %>
  <% if @logvar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@logvar.errors.count, "error") %> prohibited this logvar from being saved:</h2>

      <ul>
      <% @logvar.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :valor %><br>
    <%= f.number_field :valor %>
  </div>
  <div class="field">
    <%= f.label :fechaD %><br>
    <%= f.date_select :fechaD %>
  </div>
  <div class="field">
    <%= f.label :variable_id %><br>
    <%= f.text_field :variable_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/logvars/edit.html.erb
<h1>Editing Logvar</h1>

<%= render 'form' %>

<%= link_to 'Show', @logvar %> |
<%= link_to 'Back', logvars_path %>

app/views/logvars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Registro de Variables</h1>

<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Valor</th>
        <th>Fecha del dato</th>
        <th>Variable</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @logvars.each do |logvar| %>
        <tr>
          <td><%= logvar.valor %></td>
          <td><%= logvar.fechaD %></td>
          <td><%= logvar.variable %></td>
          <td><%= link_to '<i class="glyphicon glyphicon-eye-open" title="Mostrar"></i>', logvar %></td>
          <td><%= link_to '<i class="glyphicon glyphicon-edit" title="Editar"></i>', edit_logvar_path(logvar) %></td>
          <td><%= link_to '<i class="glyphicon glyphicon-remove-sign" title="Eliminar"></i>', logvar, method: :delete, data: { confirm: 'Estás segur@?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'Nuevo registro', new_logvar_path, class:"btn btn-warning" %>

app/views/logvars/new.html.erb
<h1>New Logvar</h1>

<%= render 'form' %>

<%= link_to 'Back', logvars_path %>

app/views/logvars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Valor:</strong>
  <%= @logvar.valor %>
</p>

<p>
  <strong>Fechad:</strong>
  <%= @logvar.fechaD %>
</p>

<p>
  <strong>Variable:</strong>
  <%= @logvar.variable %>
</p>

<%= link_to 'Edit', edit_logvar_path(@logvar) %> |
<%= link_to 'Back', logvars_path %>