config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  devise_for :users

  namespace :admin do
    resources :sessions, path: '/login', only: [:new, :create, :destroy]
    resources :users, only: [:index, :edit, :update]
  end

  resources :procesos

  resources :objetivos

  resources :indicadors do
    resources :loginds 
    resources :comments
  end
  

  resources :variables

  resources :logvars

  resources :loginds

  resources :logpros

  authenticated :user do
    root 'procesos#index', as: "authenticated_root"
  end
  
  

  root 'welcome#index'

    get '/login' => 'devise/sessions#new'

end

app/models/indicador.rb
class Indicador < ActiveRecord::Base
#asociación entre los modelos  
  belongs_to :objetivo
  has_many :commments
  has_many :variables
  has_many :loginds, dependent: :destroy

  validates :variableM, presence: true
  validates :meta, presence: true
  validates :nombre, presence: true

  accepts_nested_attributes_for :loginds,
    reject_if: proc { |attr| attr['meta'].blank? }, # comprueba si el atributo anidado está en blanco y si lo está no toma en cuenta el accept_nested_attributes_for y envia el formulario sin ellos.
    allow_destroy: true

  accepts_nested_attributes_for :variables,
    reject_if: proc { |attr| attr['nombre'].blank? }, # comprueba si el atributo anidado está en blanco y si lo está no toma en cuenta el accept_nested_attributes_for y envia el formulario sin ellos.
    allow_destroy: true

  after_create :variablePerAnt
 
  def variablePerAnt
    #if valorPerAnt != null
    #  v = variable.find(:variable_id)
    #end
  end
 
  def calculate(operator)
    # aqui se especifica operadores esperados:
    raise ArgumentError unless [:*, :+, :-, :/].include? operator.to_s
    variable.public_send(op, variables)
  end
end

app/controllers/indicadors_controller.rb
class IndicadorsController < ApplicationController
  before_action :set_indicador, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]
  # GET /indicadors
  # GET /indicadors.json
  def index
    @indicadors = Indicador.all
  end

  # GET /indicadors/1
  # GET /indicadors/1.json
  def show
   # @comments = @indicador.comments.all
    #@comment = @indicador.comments.build
   # @comments = Comment.where(indicador_id: @indicador)
  end

  # GET /indicadors/new
  def new
    @indicador = Indicador.new
    @objetivo = Objetivo.find( params[:objetivo_id])
  end

  # GET /indicadors/1/edit
  def edit
    @indicador = Indicador.find(params[:id])
    @variable = @indicador.variables.build
  end

  # POST /indicadors
  # POST /indicadors.json
  def create
    @indicador =  Indicador.new(indicador_params)
    respond_to do |format|
      if @indicador.save
        format.html { redirect_to @indicador, notice: 'El indicador fue creado exitosamente.' }
        format.json { render :show, status: :created, location: @indicador }
      else
        format.html { render :new }
        format.json { render json: @indicador.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /indicadors/1
  # PATCH/PUT /indicadors/1.json
  def update
    respond_to do |format|
      if @indicador.update(indicador_params)
      #  variable_id1 = 2
      #  variable_id2 = 1
      #  self.calcular_formula(variable_id1.to_s+" / "+variable_id2.to_s)
        format.html { redirect_to @indicador, notice: 'El indicador fue actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @indicador }
      else
        format.html { render :edit }
        format.json { render json: @indicador.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /indicadors/1
  # DELETE /indicadors/1.json
  def destroy
    @indicador.destroy
    respond_to do |format|
      format.html { redirect_to indicadors_url, notice: 'El indicador fue eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_indicador
      @indicador = Indicador.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def indicador_params
      params.require(:indicador).permit(:objetivo_id, :variableM, :nombre, :tipo, :unidad, :sentido, :importancia, :meta, :meses, :estadoA, :peorE, :formula, :fuente, :fechaI, :fechaC, variables_attributes: [:id, :nombre, :unidad, :valorPerAnt] )
    end
end

app/helpers/indicadors_helper.rb
module IndicadorsHelper
end

app/views/indicadors/_form.html.erb
 <%= form_for(@indicador) do |f| %>
    <% if @indicador.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@indicador.errors.count, "error") %> evita que el indicador sea guardado:</h2>

        <ul>
        <% @indicador.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <label class="col-sm-4 control-label">Variable de Medición</label>
      <%= f.text_field :variableM, class:"form-control-static" %>
    </div>
    <div class="form-group">
      <label class="col-sm-4 control-label">Nombre</label>
      <%= f.text_field :nombre, class:"form-control-static" %>
    </div>
    <div class="form-group">      
      <% tipos ={'Eficacia' => 'Eficacia', 'Eficiencia' => 'Eficiencia', 'Efectividad' => 'Efectividad'}%>
      <% lista = tipos.sort %>
      <label class="col-sm-4 control-label">Tipo</label>
      <%= f.select :tipo, lista, selected: "Asc"%>
    </div>
     <div class="form-group">
        <% unidades ={'Días' => 'Días', 'Pesos' => 'Pesos', 'Porcentaje' => 'Porcentaje'}%>
        <% lista = unidades.sort %>
        <label class="col-sm-4 control-label">Unidad</label>
        <%= f.select :unidad, lista, selected: "Asc"%>
    </div>
    <div class="form-group">
      <% sentidos ={'Ascendente' => 'Asc', 'Descendente' => 'Desc'}%>
      <% lista = sentidos.sort %>
      <label class="col-sm-4 control-label">Sentido</label>
      <%= f.select :sentido, lista, selected: "Asc" %>
    </div>
    <div class="form-group">
      <label class="col-sm-4 control-label">Importancia</label>
      <%= f.number_field :importancia, class:"form-control-static col-sm-2" %>
    </div>
    <div class="form-group">
      <label class="col-sm-4 control-label">Meta</label>
      <%= f.number_field :meta, class:"form-control-static col-sm-2" %>
    </div>
    <div class="form-group">
      <label class="col-sm-4 control-label">Meses</label>
      <%= f.number_field :meses, class:"form-control-static col-sm-2" %>
    </div>
    <div class="form-group">
      <label class="col-sm-4 control-label">Estado Actual</label>
      <%= f.number_field :estadoA, class:"form-control-static col-sm-2" %>
    </div>
    <div class="form-group">
      <label class="col-sm-4 control-label">Peor Escenario</label>
      <%= f.number_field :peorE, class:"form-control-static col-sm-2" %>
    </div>
    <div class="form-group">
      <label class="col-sm-4 control-label"><%= link_to 'Formula' %></label>
      <%= f.text_field :formula, class:"form-control-static" %>
    </div>
    <div class="form-group">
      <label class="col-sm-4 control-label">Fuente</label>
      <%= f.text_area :fuente, class:"form-control-static" %>
    </div>
    <div class="form-group">
      <label class="col-sm-4 control-label">Fecha de Inicio</label>
      <%= f.date_select :fechaI, {:use_month_names => ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre','Diciembre']}, class:"form-control-static" %>
    </div>
    <div class="form-group">
      <label class="col-sm-4 control-label">Fecha de Corte</label>
      <%= f.date_select :fechaC, {:use_month_names => ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre','Diciembre']}, class:"form-control-static" %>
    </div>
    <div class="actions">
      <%= f.submit class: 'btn btn-default' %>
    </div>
  <% end %>

app/views/indicadors/edit.html.erb
<div class="row">
	<div class="col-sm-7">
		<section class="containerWaterMark">
			<div class="indicador">
			<h1>Editar Indicador: <small><%= @indicador.nombre.capitalize %></small></h1>

			<p><%= render 'form' %></p>
			
			</div>
		</section>
	</div>
	<div class="col-sm-5">
		<table>
			<tr>
				<section class="containerWaterMark">					
						<%= render "variables/form" %>
					
						<div>
							<%= link_to '<button type="button">Guardar</button>'.html_safe,  class:"btn btn-warning" %>
						</div>
				</section>
			</tr>
			<tr>
				<section class="containerWaterMark">
					<div>
						<%= link_to '<button type="button">Agregar</button>'.html_safe,  class:"btn btn-warning" %>
					</div>
					<div class="form-group">
					  <label for="variables">Selecciona variable de medición:</label>
					  <select class="form-control" id="variables">
					  	<% @indicador.variables.each do |variable| %>
					    <option><%= variable.nombre %></option>
					    <% end %>
					  </select>					
					</div>
					<%= link_to '<button type="button">+</button>'.html_safe,   class:"btn btn-default" %>
					<%= link_to '<button type="button">-</button>'.html_safe,   class:"btn btn-default" %>
					<%= link_to '<button type="button">*</button>'.html_safe,   class:"btn btn-default" %>
					<%= link_to '<button type="button">/</button>'.html_safe,   class:"btn btn-default" %>
					<%= link_to '<button type="button">(</button>'.html_safe,   class:"btn btn-default" %>
					<%= link_to '<button type="button">)</button>'.html_safe,   class:"btn btn-default" %>
					<%= link_to '<button type="button">100</button>'.html_safe,   class:"btn btn-default" %>
					<%= link_to '<button type="button">CE</button>'.html_safe,   class:"btn btn-default" %>
				</section>
			</tr>
		</table>
		
	</div>
</div>
<%= link_to 'Mostrar', @indicador, class:"btn btn-warning" %> |
<%= link_to 'Atrás', indicadors_path, class:"btn btn-default" %>	

app/views/indicadors/index.html.erb
<h1>Listado de Indicadores</h1>

<div class="table-responsive">
<table class="table table-striped">
  <thead>
    <tr>
      <th>Proceso</th>
      <th>Variable de Medición</th>
      <th>Nombre de indicador</th>
      <th>Tipo</th>
      <th>Unidad</th>
      <th>Sentido</th>
      <th>% Importancia</th>
      <th>Meta</th>
      <th>Meses</th>
      <th>Estado Actual</th>
      <th>Peor Escenario</th>
      <th>Fórmula</th>
      <th>Fuente</th>
      <th>Fecha de Inicio</th>
      <th>Fecha de Corte</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @indicadors.each do |indicador| %>
      <tr>
        <td><%= indicador.objetivo.proceso.nombre %></td>
        <td><%= indicador.variableM %></td>
        <td><%= indicador.nombre %></td>
        <td><%= indicador.tipo %></td>
        <td><%= indicador.unidad %></td>
        <td><%= indicador.sentido %></td>
        <td><%= indicador.importancia %></td>
        <td><%= indicador.meta %></td>
        <td><%= indicador.meses %></td>
        <td><%= indicador.estadoA %></td>
        <td><%= indicador.peorE %></td>
        <td><%= indicador.formula %></td>
        <td><%= indicador.fuente %></td>
        <td><%= indicador.fechaI %></td>
        <td><%= indicador.fechaC %></td>
        <td><%= link_to '<i class="glyphicon glyphicon-eye-open" title="Mostrar"></i>'.html_safe, indicador %></td>
        <td><%= link_to '<i class="glyphicon glyphicon-edit" title="Editar"></i>'.html_safe, edit_indicador_path(indicador) %></td>
        <td><%= link_to '<i class="glyphicon glyphicon-remove-sign" title="Eliminar"></i>'.html_safe, indicador, method: :delete, data: { confirm: 'Estas segur@ de eliminar este indicador?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/indicadors/new.html.erb
<h1>Nuevo Indicador</h1>
  <%= form_for(@indicador, url: {action: :create}, http: {method: :post}) do |f| %>
    <% if @indicador.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@indicador.errors.count, "error") %> prohibited this indicador from being saved:</h2>
        <ul>
        <% @indicador.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-group">
      <label class="col-sm-4 control-label">Variable de Medición</label>
      <%= f.text_field :variableM, class:"form-control-static" %>
    </div>
    <div class="form-group">
      <label class="col-sm-4 control-label">Nombre</label>
      <%= f.text_field :nombre, class:"form-control-static" %>
    </div>
    <div class="form-group">      
      <% tipos ={'Eficacia' => 'Eficacia', 'Eficiencia' => 'Eficiencia', 'Efectividad' => 'Efectividad'}%>
      <% lista = tipos.sort %>
      <label class="col-sm-4 control-label">Tipo</label>
      <%= f.select :tipo, lista, selected: "Asc"%>
    </div>
     <div class="form-group">
        <% unidades ={'Días' => 'Días', 'Pesos' => 'Pesos', 'Porcentaje' => 'Porcentaje'}%>
        <% lista = unidades.sort %>
        <label class="col-sm-4 control-label">Unidad</label>
        <%= f.select :unidad, lista, selected: "Asc"%>
    </div>
    <div class="form-group">
      <% sentidos ={'Ascendente' => 'Asc', 'Descendente' => 'Desc'}%>
      <% lista = sentidos.sort %>
      <label class="col-sm-4 control-label">Sentido</label>
      <%= f.select :sentido, lista, selected: "Asc" %>
    </div>
    <div class="form-group">
      <label class="col-sm-4 control-label">Importancia</label>
      <%= f.number_field :importancia, class:"form-control-static col-sm-2" %>
    </div>
    <div class="form-group">
      <label class="col-sm-4 control-label">Meta</label>
      <%= f.number_field :meta, class:"form-control-static col-sm-2" %>
    </div>
    <div class="form-group">
      <label class="col-sm-4 control-label">Meses</label>
      <%= f.number_field :meses, class:"form-control-static col-sm-2" %>
    </div>
    <div class="form-group">
      <label class="col-sm-4 control-label">Estado Actual</label>
      <%= f.number_field :estadoA, class:"form-control-static col-sm-2" %>
    </div>
    <div class="form-group">
      <label class="col-sm-4 control-label">Peor Escenario</label>
      <%= f.number_field :peorE, class:"form-control-static col-sm-2" %>
    </div>
    <div class="form-group">
      <label class="col-sm-4 control-label"><%= link_to 'Formula' %></label>
      <%= f.text_field :formula, class:"form-control-static" %>
    </div>
    <div class="form-group">
      <label class="col-sm-4 control-label">Fuente</label>
      <%= f.text_area :fuente, class:"form-control-static" %>
    </div>
    <div class="form-group">
      <label class="col-sm-4 control-label">Fecha de Inicio</label>
      <%= f.date_select :fechaI, {:use_month_names => ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre','Diciembre']}, class:"form-control-static" %>
    </div>
    <div class="form-group">
      <label class="col-sm-4 control-label">Fecha de Corte</label>
      <%= f.date_select :fechaC, {:use_month_names => ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre','Diciembre']}, class:"form-control-static" %>
    </div>
    <div class="actions">
    	<%= f.hidden_field :objetivo_id, { value: @objetivo.id} %>
      <%= f.submit class: 'btn btn-default' %>
    </div>
  <% end %>
<%= link_to 'Atrás', indicadors_path %>

app/views/indicadors/show.html.erb
<div class="row">
  <h2 class="text-center">Proceso: <%= @indicador.objetivo.proceso.nombre.upcase %> </h2>
  <div class="col-sm-6">  
    <section class="containerWaterMark">
      <div class="indicador">
        <p>
        <h2 class="text-center">Estructura Indicador</h2>
        </p>
        <p>
        <strong>Variable de Medición:</strong>
        <%= @indicador.variableM %>
        </p>

        <p>
          <strong>Nombre:</strong>
          <%= @indicador.nombre %>
        </p>

        <p>
          <strong>Tipo:</strong>
          <%= @indicador.tipo %>
        </p>

        <p>
          <strong>Unidad:</strong>
          <%= @indicador.unidad %>
        </p>

        <p>
          <strong>Sentido:</strong>
          <%= @indicador.sentido %>
        </p>

        <p>
          <strong>Importancia:</strong>
          <%= @indicador.importancia %>
        </p>

        <p>
          <strong>Meta:</strong>
          <%= @indicador.meta %>
        </p>

        <p>
          <strong>Meses:</strong>
          <%= @indicador.meses %>
        </p>

        <p>
          <strong>Estado Actual:</strong>
          <%= @indicador.estadoA %>
        </p>

        <p>
          <strong>Peor Escenario:</strong>
          <%= @indicador.peorE %>
        </p>

        <p>
          <strong>Formula:</strong>
          <%= @indicador.formula %>
        </p>

        <p>
          <strong>Fuente:</strong>
          <%= @indicador.fuente %>
        </p>

        <p>
          <strong>Fecha de Ingreso:</strong>
          <%= @indicador.fechaI %>
        </p>

        <p>
          <strong>Fecha de Corte:</strong>
          <%= @indicador.fechaC %>
        </p>

        <%= link_to 'Editar', edit_indicador_path(@indicador), class:"btn btn-warning" %> |
        <%= link_to 'Atrás', indicadors_path, class:"btn btn-default" %>
      </div>        
    </section>
  </div>
  <div class="col-sm-6">
  <table>
      <tr>
        <section class="registrar">
          <%= link_to 'Registrar', new_logind_path(indicador_id: @indicador.id), class:"btn btn-info" %>    
        </section>
      </tr>
      <tr>
        <section class="containerWaterMark">
          <h2 class="text-center">Variables (Cuantitativas)</h2>

          <% if @indicador.variables.any? %>
            <ul>
              <% @indicador.variables.each do |variable| %>
                <li><%= link_to variable.nombre, variable %></li>
              <% end %>
            </ul>
          <% else %>
            <p> No hay variables </p>
          <% end %>
          <%= link_to 'Nueva variable', new_variable_path(@variable), class:"btn btn-warning" %>
        </section>
      </tr>
      <tr>
      
        <section id="comments" class="containerWaterMark">
            
        </section>
      </tr>
    </table>   
  </div>
</div>