config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  devise_for :users

  namespace :admin do
    resources :sessions, path: '/login', only: [:new, :create, :destroy]
    resources :users, only: [:index, :edit, :update]
  end

  resources :procesos

  resources :objetivos

  resources :indicadors do
    resources :loginds 
    resources :comments
  end
  

  resources :variables

  resources :logvars

  resources :loginds

  resources :logpros

  authenticated :user do
    root 'procesos#index', as: "authenticated_root"
  end
  
  

  root 'welcome#index'

    get '/login' => 'devise/sessions#new'

end

app/models/proceso.rb
class Proceso < ActiveRecord::Base

	belongs_to :user	


	has_many :objetivos, dependent: :destroy
	has_many :logpros, dependent: :destroy


	validates :nombre, presence: true
	validates :meta, presence: true


	accepts_nested_attributes_for :objetivos,
		reject_if: proc { |attr| attr['objetivoV'].blank? }, # comprueba si el atributo anidado está en blanco y si lo está no toma en cuenta el accept_nested_attributes_for y envia el formulario sin ellos.
		allow_destroy: true

	accepts_nested_attributes_for :logpros,
		reject_if: proc { |attr| attr['estado'].blank? }

	
	def porcentaje_importancia
		get_proceso (proc)
		@importancia = @proceso.importancia
		sum(@importancia) 
	end	

	
	private

	  def get_proceso(proc)
	    @proceso = Proceso.find(proc.to_i)
	  end

end

app/controllers/procesos_controller.rb
class ProcesosController < ApplicationController
  before_action :set_proceso, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  #before_action :authorize, except: [:show, :index]

  # GET /procesos
  # GET /procesos.json
  def index
    @procesos = Proceso.all.order('nombre ASC')
  end

  # GET /procesos/1
  # GET /procesos/1.json
  def show
    
  end

  # GET /procesos/new
  def new
    @proceso = current_user.procesos.build
    @proceso.objetivos.build #al añadir un nuevo proceso tener la posibilidad de añadir un objetivo visional en el mismo formulario
  end

  # GET /procesos/1/edit
  def edit
    @proceso.objetivos.build #permitirá agregar un nuevo objetivo visional asociado al proceso
  end

  # POST /procesos
  # POST /procesos.json
  def create
    @proceso = current_user.procesos.build(proceso_params)

    respond_to do |format|
      if @proceso.save
        format.html { redirect_to @proceso, notice: 'Proceso creado exitosamente.' }
        format.json { render :show, status: :created, location: @proceso }
      else
        format.html { render :new }
        format.json { render json: @proceso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /procesos/1
  # PATCH/PUT /procesos/1.json
  def update
    respond_to do |format|
      if @proceso.update(proceso_params)
        format.html { redirect_to @proceso, notice: 'Proceso actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @proceso }
      else
        format.html { render :edit }
        format.json { render json: @proceso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /procesos/1
  # DELETE /procesos/1.json
  def destroy
    @proceso.destroy
    respond_to do |format|
      format.html { redirect_to procesos_url, notice: 'Proceso eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proceso
      @proceso = Proceso.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proceso_params
      params.require(:proceso).permit(:nombre, :importancia, :objetivo, :meta, :fechaI, :fechaC, objetivos_attributes: [:id, :objetivoV, :_destroy])
    end

    #def authorize
     # if current_user.nil?
      #  redirect_to login_url, alert: "No estás autorizad@! Por favor inicia sesión."
      #else
       # if @proceso && @proceso.user_id != current_user
        #  redirect_to root_path, alert: "No estás autorizad@!, solo #{@proceso.user} tiene acceso a este proceso"
        #end
      #end
    #end
end

app/helpers/procesos_helper.rb
module ProcesosHelper
end

app/views/procesos/_form.html.erb
<div class="row">
  <%= form_for(@proceso) do |f| %>
    <% if @proceso.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@proceso.errors.count, "error") %> evita que este proceso sea guardado:</h2>

        <ul>
        <% @proceso.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="col-sm-6">
      <section class="containerWaterMark">
        <div class="field">
          <%= f.label :Nombre %><br>
          <%= f.text_field :nombre %>
        </div>
        <div class="field">
          <%= f.label :Importancia %><br>
          <%= f.number_field :importancia %>
        </div>
        <div class="field">
          <%= f.label :Objetivo_Misional %><br>
          <%= f.text_area :objetivo, placeholder:"Verbo Rector en Infinitivo cambiante + Variable + Cuánto + Cómo + Cuándo" %>
        </div>
        <div class="field">
          <%= f.label :Meta %><br>
          <%= f.number_field :meta, value: 1000, disabled: true %>
        </div>
        <div class="field">
          <%= f.label :Fecha_de_Inicio %><br>
          <%= f.date_select :fechaI %>
        </div>
        <div class="field">
          <%= f.label :fecha_de_Corte %><br>
          <%= f.date_select :fechaC %>
        </div>
      </section>
    </div>
    <div class="col-sm-6">
      <section class="containerWaterMark">
       <h1>Objetivos Visionales</h1>
        <%= f.fields_for :objetivos do | objetivo | %>
          <div class="objetivos_fields">
            <div class="fields">
              <%= objetivo.label :objetivoV, "Objetivo Visional" %><br>
              <%= objetivo.text_field :objetivoV,  placeholder:"Verbo Rector en Infinitivo constante + Producto + Características + Recursos + para + impacto esperado" %>
              <%= objetivo.check_box :_destroy %>
              <%= objetivo.label :_destroy, 'eliminar' %>
            </div>    
          </div>
        <% end %>
      </section>
      
      <div class="actions">
        <%= f.submit %>
      </div>
    </div>
  <% end %>
</div>

app/views/procesos/edit.html.erb
<section class="containerSession">
	<h1>Editando Proceso: <%= @proceso.nombre.capitalize %></h1>

	<%= render 'form' %>
</section>

<%= link_to 'Mostrar', @proceso, class:"btn btn-warning" %> |
<%= link_to 'Atrás', procesos_path, class:"btn btn-default" %>

app/views/procesos/index.html.erb
  <% if user_signed_in? %>
    <%-# Tabla de estructura de procesos -%>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Usuario</th>
          <th>Nombre</th>
          <th>Importancia</th>
          <th>Objetivo</th>
          <th>Fecha de Inicio</th>
          <th>Fecha de Corte</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @procesos.each do |proceso| %>
          <tr>
            <td><%= proceso.user.name1.capitalize + " " + proceso.user.ape1.capitalize %></td>
            <td><%= proceso.nombre %></td>
            <td><%= proceso.importancia %></td>
            <td><%= proceso.objetivo %></td>
            <td><%= proceso.fechaI %></td>
            <td><%= proceso.fechaC %></td>
            <td><%= link_to '<i class="glyphicon glyphicon-eye-open" title="Mostrar"></i>'.html_safe, proceso %></td>
            <% if proceso.user == current_user %>
            <td>              
              <%= link_to '<i class="glyphicon glyphicon-edit" title="Editar"></i>'.html_safe, edit_proceso_path(proceso) %>              
            </td>
            <td>              
              <%= link_to '<i class="glyphicon glyphicon-remove-sign" title="Eliminar"></i>'.html_safe, proceso, method: :delete, data: { confirm: 'Estas segur@ de eliminar este proceso?' } %>
            </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
    <br>
   
    <% if current_user %>
    <%= link_to 'Nuevo Proceso', new_proceso_path, class: "btn btn-warning" %>
    
      
    
      <%-# Resumen Empresarial -%>
      <h1>Registros procesos: </h1>
        <table class="table table-bordered table-hover ">
          <thead>
            <tr> 
              <th>Procesos</th>
              <th>Ene</th>
              <th>Feb</th>
              <th>Mar</th>
              <th>Abr</th>
              <th>May</th>
              <th>Jun</th>
              <th>Jul</th>
              <th>Ago</th>
              <th>Sep</th>
              <th>Oct</th>
              <th>Nov</th>
              <th>Dic</th>
              <th>% importancia</th>        
            </tr>              
          </thead>

          <tbody>    
          
          </tbody>
        </table>
      <br>
    <% end %>
    
    <%elsif%>
      <%-# Si no se inicia sesión, se puede ver un resumen general de los procesos de la organización -%>
      <h1>Procesos</h1>
        <% @procesos.each do |proceso| %>
        <div class="col-md-3 thumbnail">                    
          <article class="item proceso">
            <p class="valor"><%= proceso.meta %></p>
              <h2 class="text-center"><%= link_to proceso.nombre, proceso %></h2>
                <button type="button" class="btn btn-primary">meta: <span class="badge"><%= proceso.meta %></span></button>
              <p> <%= time_ago_in_words(proceso.created_at) %> </p>
          </article>  
        </div>
    <%end%>
<%end%>

app/views/procesos/new.html.erb
<section>
	<h1>Nuevo Proceso</h1>

		<%= render 'form' %>

</section>

<%= link_to 'Atrás', procesos_path, class:"btn btn-default" %>

app/views/procesos/show.html.erb
<p>  
  <h1>Proceso: <%= @proceso.nombre %></h1>
</p>
<p>Lider de proceso: <%= @proceso.user.name1.capitalize + " " + @proceso.user.ape1.capitalize %></p>
<p>Objetivo Misional: <%= @proceso.objetivo %></p>

<section>
  <h2>Objetivos Visionales</h2>

  <% if @proceso.objetivos.any? %>
    <ul>
      <% @proceso.objetivos.each do |objetivo| %>
        <li><%= link_to objetivo.objetivoV, objetivo %></li>
      <% end %>
    </ul>
  <% else %>
    <p> No hay Objetivos misionales </p>
  <% end %>
</section>

<section>
  <h3>Registros</h3>  

  <% if @proceso.objetivos.any? %>
    <div class="table-responsive">
      <table class="table table-bordered">
        <thead class="open">
          <% @procesos.objetivos.indicador.each do |indicador| %> 
          <tr>
            <th><%= indicador.nombre %></th>
          </tr> 
          <% end %>
        </thead>
        <tbody>
          <% for n in (10..1) %>
          <tr>
            <td><%= n %></td>            
          </tr>         
          <% end %>
        </tbody>
      </table>
    </div>
    <% else %>
      <p>no hay registros</p>
    <% end %>
</section>

<div id="popup" style="display: none;">
    <div class="content-popup">
        <div class="close"><a href="#" id="close"></a></div>
        <div>
           <h2>Cuadro general de indicadores</h2>
           <table>
             <thead>
               <th>indicador</th>
             </thead>
             <tbody>
               <tr><td>puntaje</td></tr>
             </tbody>
           </table>
        </div>
    </div>
</div>


<%= link_to 'Todos los procesos', procesos_path, class: "btn btn-info"  %>
<% if current_user && @proceso.user_id == current_user %>
  <%= link_to 'Editar', edit_proceso_path(@proceso), class: "btn btn-warning" %>
<% end %> |
<%= link_to 'Atrás', procesos_path, class: "btn btn-default" %>