config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  devise_for :users

  namespace :admin do
    resources :sessions, path: '/login', only: [:new, :create, :destroy]
    resources :users, only: [:index, :edit, :update]
  end

  resources :procesos

  resources :objetivos

  resources :indicadors do
    resources :loginds 
    resources :comments
  end
  

  resources :variables

  resources :logvars

  resources :loginds

  resources :logpros

  authenticated :user do
    root 'procesos#index', as: "authenticated_root"
  end
  
  

  root 'welcome#index'

    get '/login' => 'devise/sessions#new'

end

app/models/variable.rb
class Variable < ActiveRecord::Base

belongs_to :indicador

end

app/controllers/variables_controller.rb
class VariablesController < ApplicationController
  before_action :set_variable, only: [:show, :edit, :update, :destroy]

  # GET /variables
  # GET /variables.json
  def index
    @variables = Variable.all
  end

  # GET /variables/1
  # GET /variables/1.json
  def show
  end

  # GET /variables/new
  def new
    @variable = Variable.new
  end

  # GET /variables/1/edit
  def edit
  end

  # POST /variables
  # POST /variables.json
  def create
    @variable = Variable.new(variable_params)

    respond_to do |format|
      if @variable.save
        format.html { redirect_to @variable, notice: 'Variable creada exitosamente.' }
        format.json { render :show, status: :created, location: @variable }
      else
        format.html { render :new }
        format.json { render json: @variable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /variables/1
  # PATCH/PUT /variables/1.json
  def update
    respond_to do |format|
      if @variable.update(variable_params)
        format.html { redirect_to @variable, notice: 'Variable actualizada exitosamente.' }
        format.json { render :show, status: :ok, location: @variable }
      else
        format.html { render :edit }
        format.json { render json: @variable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /variables/1
  # DELETE /variables/1.json
  def destroy
    @variable.destroy
    respond_to do |format|
      format.html { redirect_to variables_url, notice: 'Variable eliminada exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_variable
      @variable = Variable.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def variable_params
      params.require(:variable).permit(:nombre, :unidad, :valorPerAnt)
    end
end

app/helpers/variables_helper.rb
module VariablesHelper
end

app/views/variables/_form.html.erb
<%= form_for(@variable) do |f| %>
  <% if @variable.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@variable.errors.count, "error") %> prohibited this variable from being saved:</h2>

      <ul>
      <% @variable.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="panel panel-default var">
    <div class="panel-heading">Variables</div>
    <div class="panel-body">
      <div class="field">
        <%= f.label :Nombre %><br>
        <%= f.text_field :nombre %>
      </div>
      <div class="field">      
        <% unidades ={'Días' => 'Días', 'Pesos' => 'Pesos', 'Porcentaje' => 'Porcentaje'}%>
        <% lista = unidades.sort %>
        <%= f.label :Unidad %><br>
        <%= f.select :unidad, lista, selected: "Asc"%>
      </div>
      <div class="field">
        <%= f.label :Valor_Periodo_Anterior %><br>
        <%= f.text_field :valorPerAnt %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
    </div>
  </div>
    
<% end %>

app/views/variables/edit.html.erb
<h1>Edición de Variable</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @variable, class:"btn btn-warning" %> |
<%= link_to 'Atrás', variables_path, class:"btn btn-default" %>

app/views/variables/index.html.erb
<h1>Listado de Variables</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Unidad</th>
      <th>Valor Periodo Anterior</th>
      <th>Indicador</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @variables.each do |variable| %>
      <tr>
        <td><%= variable.nombre %></td>
        <td><%= variable.unidad %></td>
        <td><%= variable.valorPerAnt %></td>
        <td><%= variable.indicador_id %></td>
        <td><%= link_to '<i class="glyphicon glyphicon-eye-open" title="Mostrar"></i>'.html_safe, variable %></td>
        <td><%= link_to '<i class="glyphicon glyphicon-edit" title="Editar"></i>'.html_safe, edit_variable_path(variable) %></td>
        <td><%= link_to '<i class="glyphicon glyphicon-remove-sign" title="Eliminar"></i>'.html_safe, variable, method: :delete, data: { confirm: 'Estás segur@ de eliminar esta variable?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Variable', new_variable_path, class:"btn btn-warning" %>

app/views/variables/new.html.erb
<h1>Nueva Variable(Cuantitativa)</h1>

<%= render 'form' %>

<%= link_to 'Atrás', variables_path,  class:"btn btn-default" %>

app/views/variables/show.html.erb
<section class="containerWaterMark">
	<p>
	  <strong>Nombre:</strong>
	  <%= @variable.nombre %>
	</p>
	<p>
	  <strong>Unidad:</strong>
	  <%= @variable.unidad %>
	</p>

	<p>
	  <strong>Valor periodo anterior:</strong>
	  <%= @variable.valorPerAnt %>
	</p>
</section>

<%= link_to 'Editar', edit_variable_path(@variable),  class:"btn btn-warning" %> |
<%= link_to 'Atrás', variables_path,  class:"btn btn-default" %>